# =============================================================================
# Marmelado OS — LightDM GTK Greeter Theme
# =============================================================================

[greeter]
background=/usr/share/marmelado/wallpaper/helldivers-wallpaper.jpg
theme-name=Adwaita-dark
icon-theme-name=Papirus-Dark
font-name=Sans 11
xft-antialias=true
xft-hintstyle=slight
xft-rgba=rgb

# Marmelado logo above login box
logo=/usr/share/marmelado/logo/marmelado-logo.png

# Position the login box center
position=50%,center 50%,center

# Show clock
clock-format=%H:%M — %A, %d. %B %Y

# Clean panel at top
panel-position=top
indicators=~spacer;~clock;~spacer;~session;~a11y;~power
