# =============================================================================
# Marmelado OS — LightDM Configuration
# =============================================================================

[LightDM]
run-directory=/run/lightdm
sessions-directory=/usr/share/lightdm/remote-sessions:/usr/share/xsessions
greeter-session=lightdm-gtk-greeter
user-session=xfce

[Seat:*]
greeter-session=lightdm-gtk-greeter
session-wrapper=/etc/lightdm/Xsession
display-setup-script=
autologin-user=
autologin-user-timeout=0
