# =============================================================================
# Marmelado OS — NetworkManager: Privacy DNS (Quad9)
# /etc/NetworkManager/conf.d/dns-quad9.conf
# =============================================================================

[global-dns-domain-*]
servers=9.9.9.9,149.112.112.112

[main]
dns=default
