# =============================================================================
# Marmelado OS — NetworkManager: MAC Randomization
# /etc/NetworkManager/conf.d/mac-randomize.conf
# =============================================================================

[device]
wifi.scan-rand-mac-address=yes

[connection]
wifi.cloned-mac-address=random
ethernet.cloned-mac-address=random
connection.stable-id=${CONNECTION}/${BOOT}
